### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by paulous** [rvanasa/vite-react-motoko#1]
I am getting this error when I click on the "count" button:

16:30:17 [vite] http proxy error at /api/v2/canister/rrkah-fqaaa-aaaaa-aaaaq-cai/call:
Error: connect ECONNREFUSED ::1:4943
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) (x4)

and this error in the console:

index.ts:514  GET http://localhost:3000/api/v2/status 500 (Internal Server Error)
Unable to fetch root key. Check to ensure that your local replica is running

The project is deployed and running.

**Comment by rvanasa** [comment]
Thanks for the bug report!

What operating system and `dfx` / Node.js versions are you using so I can try to recreate this on my end? 

Also, is it possible access Candid UI on port 4943? Otherwise, this is most likely an issue with Vite's HTTP proxy.

**Comment by paulous** [comment]
Glad to help!
I am using kde manjaro and my node version is: v19.6.0, dfx version 0.12.1

So if I go to: http://127.0.0.1:4943/?<canisterId> all is well.

If I npm start and go to http://localhost:3000/ I get this terminal error:

19:42:17 [vite] http proxy error at /api/v2/canister/rrkah-fqaaa-aaaaa-aaaaq-cai/call:
Error: connect ECONNREFUSED ::1:4943
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) (x4)

and this browser error:

index.ts:347 Server returned an error:
  Code: 500 (Internal Server Error)
  Body: 
  Retrying request.
_requestAndRetry @ index.ts:347
:3000/api/v2/canister/rrkah-fqaaa-aaaaa-aaaaq-cai/call:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.ts:350 Uncaught (in promise) Error: Server returned an error:
  Code: 500 (Internal Server Error)
  Body: 

    at HttpAgent._requestAndRetry (index.ts:350:15)
    at async HttpAgent._requestAndRetry (index.ts:348:16)
    at async HttpAgent._requestAndRetry (index.ts:348:16)
    at async HttpAgent._requestAndRetry (index.ts:348:16)
    at async Promise.all (:3000/index 0)
    at async HttpAgent.call (index.ts:321:35)
    at async caller (actor.ts:360:39)
    at async increment (App.tsx:29:7)

there is more if needed but I think that about covers it.

Thanks!

**Comment by rvanasa** [comment]
Thank you for the information! I will be at the ETHDenver convention until March 5, so here are a few debugging suggestions until I get a chance to look into this more deeply:

- The relevant proxy server code is in the top-level [`vite.config.ts`](https://github.com/rvanasa/vite-react-motoko/blob/main/vite.config.ts#L42-L43) file. You could try replacing `localhost` with `127.0.0.1` or uncommenting `changeOrigin: true` in case this happens to fix the issue. 
- [`@dfinity/agent`](https://npmjs.com/package/@dfinity/agent) currently has some known issues with Node 19. About a month ago, somebody fixed a similar problem by downgrading to Node 18.x, so perhaps you could try this if necessary.

**Comment by paulous** [comment]
Thanks I'll check those out. Have fun at the convention.

Just so you know. I tried both the vite.config and uncommenting with the same result.
I don't get the error when I dfx new project so not sure if it would be dfinity/agent.

**Comment by rvanasa** [comment]
I was able to reproduce the issue by switching to Node 19. The [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware#readme) package (used by [Vite](https://github.com/vitejs/vite#readme) under the hood) no longer recognizes "localhost" as a valid hostname, so the fix was to replace `http://localhost:4943` with `http://127.0.0.1:4943` in `vite.config.ts`. Feel free to pull the changes, and let me know if this works for you!

**Comment by rvanasa** [comment]
Closing; if anyone runs into a similar error, please let me know and I will reopen the issue.
