### ISSUE TITLE
dfx 0.15.1 cpu usage

### ISSUE THREAD

**Issue by paulous** [rvanasa/vite-react-motoko#7]
Hi, I'm getting huge cpu drain from dfx when i deploy the setup. Seems ok when I deploy but when I `npm start` that kicks off the cpu drain. I am using the latest node.

**Comment by rvanasa** [comment]
Thanks for the report. Is this new to dfx 0.15.1? I'll take a look at this when I get an opportunity.

**Comment by paulous** [comment]
No worries! I was using your setup before dfx 0.15.1? and I wasn't getting the cpu increase. I have only tested it with this machine though.

**Comment by rvanasa** [comment]
I'm trying to recreate this on my end, and the CPU usage seems to be about the same between 0.15.0 and 0.15.1 on my macOS laptop. Here are some follow-up questions:

- Are you still using KDE Manjaro?
- Does this happen with the default starter project (without any code changes)? 
- Do you get any unusual CPU usage when running `dfx generate`? 

For a bit of background in case it helps narrow down the problem, `npm start` is a live-reload dev server which runs `dfx generate backend` and `dfx deploy backend` upon Motoko file change within the workspace. It might be worth individually removing the `--generate` and `--deploy` flags in the `"backend"` npm script (defined in `package.json`) to see if either of those commands are causing most of the CPU usage.

**Comment by paulous** [comment]
YES - Are you still using KDE Manjaro?
WILL TEST AGAIN (think yes) - Does this happen with the default starter project (without any code changes)?
NO - Do you get any unusual CPU usage when running dfx generate?

Thanks for the tips. I'm having a hard time finding a react template that behaves well with II and is very basic that I can update. I tried pulling deps for II and this may have made the cpu go up. Not sure will try again and let you know if I get more issues.

Thanks!

**Comment by paulous** [comment]
Seems to be working now. I think my issues are else where with II implementation. Thanks again!

**Comment by rvanasa** [comment]
Glad it worked out! Cheers!

> I'm having a hard time finding a react template that behaves well with II and is very basic that I can update.

Noted; I'll see if we can increase the priority of building (or improving) an official II example project.

**Comment by paulous** [comment]
I have it up and working with II now. CPU is good, all good. Thanks, and great template.
